config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :cards do
    scope module: :cards do
      resource :pop,           only: :update
      resource :pin,           only: :update
      resource :archive,       only: :update
      resource :cardable_type, only: :update
      resource :completion,    only: [ :create, :destroy ]
    end
  end
  resources :popped, only: :index
  resources :tags
  resources :streams
  resource :calendar, only: :show
  resources :pinned, only: :index
  get "cards/cardable_types/:id", to: "cards/cardable_types#show", as: :card_type_fields

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div style="display: flex; gap: 1rem; padding: 1rem; box-sizing: border-box;">
  <div style="position: relative; display: flex, flex-direction: column; justify-content: space-between; flex: 1; height: 80vh; position: sticky; top: 0; width: 100%; flex-shrink: 0; overflow-y: auto; border: 1px solid #ccc; padding: 1rem; border-radius: 0.5rem;"w>
    <%= turbo_frame_tag "streams_panel", src: streams_path, loading: :eager do %>
      <p>Loading streams...</p>
    <% end %>

    <div style="position: absolute; bottom: 2px; flex: 1; overflow-y: auto; border: 1px solid #ccc; padding: 1rem; border-radius: 0.5rem;">
      <%= turbo_frame_tag "pins_panel", src: pinned_index_path, loading: :eager do %>
        <p>Loading pinned cards...</p>
      <% end %>
    </div>
  </div>

  <div style="flex: 1; height: 100%; width: 100%; max-width: 680px; flex-shrink: 0; padding: 1rem; border-radius: 0.5rem;">
    <%= turbo_frame_tag "cards_panel", src: cards_path, loading: :eager do %>
      <p>Loading cards...</p>
    <% end %>
  </div>

  <div style="flex: 1; display: flex; flex-direction: column; gap: 1rem; height: 50vh; position: sticky; top: 0; width: 100%; flex-shrink: 0;">

    <div style="flex: 1; overflow-y: auto; border: 1px solid #ccc; padding: 1rem; border-radius: 0.5rem;">
      <%= turbo_frame_tag "calendar_panel", src: calendar_path, loading: :eager do %>
        <p>Loading calendar...</p>
      <% end %>
    </div>
  </div>
</div>